### ISSUE TITLE
Timer only change manual doesn't work properly

### ISSUE THREAD

**Issue by XardoniK** [DanielYKPan/date-time-picker#169]
I have problem with time picker. When i set type="timer" I can't change time in input manually. Changing time in input resetting field. Type="both" work great.

**Comment by DanielYKPan** [comment]
Have you tried the DEMO? And it works fine in time only version

**Comment by XardoniK** [comment]
Yes, I tried. But if you set readOnly="true" and change value in input it doesn't update inputs in your timepicker like in type="both"

**Comment by DanielYKPan** [comment]
@XardoniK 
I tested it, and it worked fine.
You may produced a git repo or a Plunker to demonstrate the issue.

**Comment by XardoniK** [comment]
Okay, https://plnkr.co/edit/txdaIi?p=preview
1.
![image](https://user-images.githubusercontent.com/9059223/31760675-c4964e30-b4b5-11e7-9278-0c7893b000e1.png)

2.
![image](https://user-images.githubusercontent.com/9059223/31760686-cf9e6362-b4b5-11e7-85ef-c3c5cfc57c48.png)

3.
![image](https://user-images.githubusercontent.com/9059223/31760704-da1463d2-b4b5-11e7-9a2a-7a86b6566636.png)

4.
![image](https://user-images.githubusercontent.com/9059223/31760707-e068a3a6-b4b5-11e7-9ad6-ec03a3cd53ac.png)


Second picker

![image](https://user-images.githubusercontent.com/9059223/31760744-fa39b7b6-b4b5-11e7-8968-95e281a5249a.png)

![image](https://user-images.githubusercontent.com/9059223/31760751-066cfba6-b4b6-11e7-9f42-3f42e540ca59.png)

**Comment by DanielYKPan** [comment]
@XardoniK 
I see. This is due to the limitation of date-fns parse() function. In date-fns, parse() doesn't accept a format string, and it only parse a string to Javascript Date Object if a string contains date and time.
In date-fns version 2, it would solve this issue, but it still in prerelease stage. I would try to update date-fns to version 2, and see if it will break other parts of the picker.

**Comment by DanielYKPan** [comment]
Update to latest version, it should be fixed

**Comment by jmejiaz** [comment]
Hi, I have this version 5.0.0-beta.12, and the problem is still there
