### ISSUE TITLE
Wrong value is set when click on clear button

### ISSUE THREAD

**Issue by guidosreis** [DanielYKPan/date-time-picker#183]
After selecting some date, model value is write (see devtools),
![image](https://user-images.githubusercontent.com/17104317/32445519-18d73c08-c2ed-11e7-8b74-dd986987e346.png)

But, when click on clear button, a crazy datetime is set to model value, when it must bee an empty string (see devtools)
![image](https://user-images.githubusercontent.com/17104317/32445530-298233c8-c2ed-11e7-9883-9b818205f864.png)

Any idea on how to fix this behavior??

**Comment by DanielYKPan** [comment]
Update to latest version, it should be fixed

**Comment by guidosreis** [comment]
The problem persist even updating to the latest version, when dataType is set to string.
