### ISSUE TITLE
dialog always on the background

### ISSUE THREAD

**Issue by paulimfavarato** [DanielYKPan/date-time-picker#237]
I have a bootstrap 4 modal with this picker. The picker always opens on the background of elements.
![capturar](https://user-images.githubusercontent.com/1192776/35039567-600c5238-fb65-11e7-9d59-03c06a5b080d.PNG)
There are any solution? The old picker didn't have this issue.

**Comment by DanielYKPan** [comment]
you might consider set a appropriate z-index for the picker in your case

**Comment by paulimfavarato** [comment]
i tried everything. but nothing. the modal and the picker is put directly child of body. the modal always os displayed over the picker

**Comment by promentol** [comment]
<img width="789" alt="screen shot 2018-01-20 at 5 32 39 pm" src="https://user-images.githubusercontent.com/6441936/35183977-4c1563d2-fe08-11e7-9df0-da4e3680951d.png">
I can confirm same issue with Angular Material's dialog.
Unfortunately setting z-index something very big didn't get any result

**Comment by paulimfavarato** [comment]
this issue should be open

**Comment by DanielYKPan** [comment]
As you can see in the dom, material dialog is added outside the app's dom. But the picker is added is the app's, therefore it is always behind the material dialog no matter the z-index you set.
In this case, you might consider use the material datepicker.

**Comment by paulimfavarato** [comment]
i'm using the previous version. It works well

**Comment by DanielYKPan** [comment]
Yes, in 5.1.0, the picker is added in a overlay which is similar to angular material

**Comment by DanielYKPan** [comment]
The background issue has been fixed in the latest version(5.1.1)

**Comment by paulimfavarato** [comment]
thank tou!

**Comment by paulimfavarato** [comment]
unfortunately it isn't fixed. the background issue persists.

**Comment by DanielYKPan** [comment]
It has been fixed with the material dialog issue as @promentol mentioned about.

I haven't tested it with the bootstrap 4

**Comment by DanielYKPan** [comment]
@paulimfavarato 
Come on man, setting the z-index works in your case.

As I tested it in bootstrap 4 modal,
bootstrap 4 modal has z-index : 1040 (as default)

You just need to set the class 'cdk-overlay-container' with a z-index greater than 1040
